[package]
name = "ascii-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.26.1"
image = "0.24.6"
nokhwa = { version = "0.10.3", features = ["input-v4l"]}
tui = "0.19.0"
